"""Create ES-DE launchers for installed PC games.

ES-DE's `windows` system only accepts .bat and .lnk files, so a game that was
installed or extracted into a folder is invisible until something points at its
executable. This module finds that executable and writes the launcher.

A .bat is used rather than a .lnk: it needs no COM, it is readable and
diffable, and cmd waits for the game to exit so ES-DE sees the real session
length.
"""

from __future__ import annotations

import re
from pathlib import Path

#: Executables that are never the game itself.
_NOT_THE_GAME = re.compile(
    r"(unins|setup|install|redist|vcredist|directx|dxsetup|dotnet|crash|report|"
    r"launcher_?config|config|settings|update|patch|helper|service)", re.I)

#: Names that usually *are* the game when several candidates tie.
_LIKELY = re.compile(r"(game|start|play|launch)", re.I)

LAUNCHER_SUFFIX = ".bat"


def find_executables(game_dir: Path) -> list[Path]:
    """Plausible game executables inside a folder, best candidate first."""
    if not game_dir.is_dir():
        return []
    exes = [p for p in game_dir.rglob("*") if p.is_file() and p.suffix.lower() == ".exe"]
    exes = [p for p in exes if not _NOT_THE_GAME.search(p.stem)]

    def rank(p: Path) -> tuple:
        depth = len(p.relative_to(game_dir).parts)
        name_match = 0 if _LIKELY.search(p.stem) else 1
        # Prefer shallow, likely-named, then larger binaries.
        try:
            size = -p.stat().st_size
        except OSError:
            size = 0
        return (depth, name_match, size)

    return sorted(exes, key=rank)


def bat_contents(exe: Path) -> str:
    """A launcher that runs the game from its own directory and waits for it."""
    return (
        "@echo off\r\n"
        "rem Generated by esdeck - safe to edit or delete.\r\n"
        f'cd /d "{exe.parent}"\r\n'
        f'"{exe}" %*\r\n'
    )


def write_launcher(dest: Path, exe: Path, *, dry_run: bool = False,
                   overwrite: bool = False) -> str:
    if dest.exists() and not overwrite:
        return f"exists, left alone: {dest.name}"
    if not dry_run:
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(bat_contents(exe), encoding="utf-8")
    return f"{dest.name} -> {exe}"


def scan_install_dir(install_dir: Path, rom_dir: Path) -> list[dict]:
    """One record per installed PC game folder, with its launcher status."""
    install_dir, rom_dir = Path(install_dir), Path(rom_dir)
    if not install_dir.is_dir():
        return []
    target_dir = rom_dir / "windows"
    out = []
    for folder in sorted(p for p in install_dir.iterdir() if p.is_dir()):
        exes = find_executables(folder)
        dest = target_dir / f"{folder.name}{LAUNCHER_SUFFIX}"
        out.append({
            "name": folder.name,
            "folder": folder,
            "candidates": exes,
            "dest": dest,
            "has_launcher": dest.exists() or (dest.with_suffix(".lnk")).exists(),
        })
    return out
